include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: false
    avoid_print: true
    prefer_final_locals: true
    require_trailing_commas: true
