name: meinimpact
description: Cross-platform civic action assistant.
publish_to: none
version: 0.1.1+2

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  intl: any

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
